### ISSUE TITLE
Response constructor should handle SharedArrayBuffer

### ISSUE THREAD

**Issue by RReverser** [whatwg/fetch#1004]
Currently you can construct a `Response` from an `ArrayBuffer` and it will correctly copy the contents.

However, if you try to construct a `Response` from a `SharedArrayBuffer`, it seems to stringify the object, resulting in `[object SharedArrayBuffer]`, and then uses that string as a source data. https://twitter.com/RReverser/status/1233446149291417605

This behaviour can be quite surprising and it seems that the constructor should either clone data from `SharedArrayBuffer` upon creation or explicitly reject it with a `TypeError`.

**Comment by jakearchibald** [comment]
https://heycam.github.io/webidl/#AllowShared

I wonder why this isn't the default? Maybe because with sharedarraybuffer, the data could be modified during the copy operation.

**Comment by annevk** [comment]
1. I think that per IDL due to lack of `[AllowShared]` it should already throw. Firefox had a bug here that was just fixed: https://bugzilla.mozilla.org/show_bug.cgi?id=1615741. (Not that we ship `SharedArrayBuffer` yet, but still.)
2. As shared memory is potentially dangerous, it cannot be the default and needs to be a somewhat informed and auditable decision.
3. If copy semantics are what we want here (and not sure anything else makes sense), it seems fine to add [AllowShared]` here. Probably want a more complete evaluation of the entire API surface though to see what changes to make for shared memory.

**Comment by jakearchibald** [comment]
We use copy semantics for non-shared buffers right?

**Comment by annevk** [comment]
We do, though https://fetch.spec.whatwg.org/#concept-bodyinit-extract really ought to reference https://heycam.github.io/webidl/#dfn-get-buffer-source-copy.

**Comment by annevk** [comment]
Let's fold this into #897. If we do it we should probably tackle all of them at the same time.
