### ISSUE TITLE
Polyfill abandoned

### ISSUE THREAD

**Issue by wheresrhys** [whatwg/fetch#1027]
It looks like the official* polyfill has been abandonded by github https://github.com/github/fetch/issues/777. Is this something that any of the admins of this project have any influence over?

*or is it semi-official? The package name is whatwg-fetch, so it at least looks official

**Comment by sideshowbarker** [comment]
It‘s not official at all, no even semi-official.

Nobody from the WHATWG was involved in developing it. I guess it ended up with the `whatwg-fetch` name because at the time they created it, a `fetch` package already existed (and maybe `isomorphic-fetch` too?) — so the intent of the package name was just to distinguish it from the other packages by identifying it as “the fetch API based on the WHATWG spec”.

**Comment by annevk** [comment]
Indeed, if there's an implementation we attempt to maintain as part of the standardization process that would be mentioned in the README (see whatwg/url for instance).
