### ISSUE TITLE
"get, decode, and split" seems incorrect

### ISSUE THREAD

**Issue by annevk** [whatwg/fetch#1068]
It's wrong for X-Content-Type-Options, but it seems wrong for other callers too. E.g., we don't want to support `Content-Type: "text/html"`.

What needs to happen is that this algorithm preserves the quotes in the output. It needs to be aware of them to ensure they are matched up with another quote, but it shouldn't end up stripping them.

**Comment by domenic** [comment]
Hmm. The examples table actually seems to preserve the quotes in the output, but the algorithm (in particular the call-out to https://fetch.spec.whatwg.org/#collect-an-http-quoted-string) seems to strip them.

In a vacuum, I'd prefer treating quoted and non-quoted values identically. For example it seems strange that a spec would have to define the set of allowed values as something like `x`, `y`, `"z,w"` instead of `x`, `y`, `z,w`.

But, it sounds like that isn't how the world works, so OK.

Are there examples of callers that actually expect quoted strings?

**Comment by annevk** [comment]
Well, `Content-Type` in a way, as `text/html;charset="utf-8"` ought to work. And if the parser did preserve things, it would also work for `X-Content-Type-Options` as it would simply not result in a match. (When you do want it to result in a match you can use https://fetch.spec.whatwg.org/#collect-an-http-quoted-string with the extract-value flag as parse a MIME type does.

**Comment by domenic** [comment]
> Well, Content-Type in a way, as `text/html;charset="utf-8"` ought to work.

I don't think this example illustrates the issue. Get, decode, and split would preserve those quotes either way. Currently it only strips quotes at the beginning and end of a comma-separated segment.

I suspect there is nothing in the platform that actually consumes outputs from get, decode, and split where one of the list members is expected to start and end with a quote. (E.g., because that list member contains a comma.)

From another angle:

I agree that preserving quotes will make the existing parts of the platform work better. My concern was about a hypothetical part of the platform, e.g. some header whose value space was `x`, `y`, or `"z,w"`. Preserving quotes would work slightly worse for such a header. But, probably no such headers exist, and if they come to exist in the future, we'll deal with it.

**Comment by annevk** [comment]
Hopefully in the future we'll only have structured fields to (mostly not) deal with. 😊

**Comment by annevk** [comment]
Oh wait, I think the current algorithm is fine after all as we don't pass the extract-value flag. Any ideas for how to improve the readability?

**Comment by domenic** [comment]
Hmm, I see.

Well, we've got an instance of https://github.com/whatwg/infra/issues/320 here with the extract-value flag.

Additionally, the note

> The extract-value flag argument makes this algorithm suitable for getting, decoding, and splitting and parse a MIME type, as well as other header value parsers that might need this. 

is misleading, since getting, decoding, and splitting explicitly does *not* use the flag. I'd suggest something like

> The extract-value flag gives the value inside the quotes, with any nested quotes unescaped.
