### ISSUE TITLE
"Return a network error" doesn't seem to go through "process response"

### ISSUE THREAD

**Issue by domenic** [whatwg/fetch#1164]
Consider what happens when we reach step 10 of `fetch()`, which calls the "fetch" algorithm.

The only way the promise ever gets resolved or rejected is once "process response" gets invoked.

However, it's possible to (synchronously) reach a step which reads "Return a network error", e.g. fetch step 2.3, or main fetch step 3.2, 3.3. In which case "process response" never gets invoked, so in theory the promise doesn't settle.

**Comment by annevk** [comment]
Thanks! This is a regression from the "abort when" language that was added. We probably should not use that language before going in parallel. That does assume that fetch and terminate are invoked from the same thread, but that's hopefully reasonable?

cc @jakearchibald

**Comment by jakearchibald** [comment]
> We probably should not use that language before going in parallel

This is sort-of related to https://github.com/whatwg/fetch/issues/536, since there are specs which call fetch in parallel. I guess we could pretend that they don't for now, then figure out a way that fetch should be called in parallel.

If we're assuming that fetch must be called from the main thread, I can just remove the abort language from those parts. Sound good?

**Comment by annevk** [comment]
I will take care of this as part of that issue. My idea is that for "in parallel" invocation of fetch you still have to give callbacks that will be called in a parallel queue that fetch creates. And there is no more returning of a response to the caller.

**Comment by jakearchibald** [comment]
Sounds good. I'll remove the abort stuff.

**Comment by jakearchibald** [comment]
No I won't (following IRC chat)
