### ISSUE TITLE
Update RFC 7234 usage to RFC 9111

### ISSUE THREAD

**Issue by dlrobertson** [whatwg/fetch#1558]
[RFC 7234] has been obsoleted by [RFC 9111]. Replace links to [RFC 7234] with the appropriate sections in [RFC 9111].

[RFC 7234]: https://www.rfc-editor.org/rfc/rfc7234.html
[RFC 9111]: https://www.rfc-editor.org/rfc/rfc9111.html

**Comment by dlrobertson** [comment]
On a cursory glance things largely look the same. [stale-while-revalidate](https://www.rfc-editor.org/rfc/rfc5861#section-3) is not listed in [Cache Directive Registration](https://www.rfc-editor.org/rfc/rfc9111#name-cache-directive-registratio), but is still listed in [IANA HTTP Cache Directive Registry](https://www.iana.org/assignments/http-cache-directives/http-cache-directives.xhtml). I don't really know how changes like this work, so I'm likely missing something.

**Comment by annevk** [comment]
One thing I wanted to do as part of this is to acknowledge the new header terminology, which would make this less straightforward than updating the links. (Essentially, HTTP calls most of them fields now and we should probably start using that or at least acknowledge that but say we'll continue using header.)

Something similar might apply to header values as we don't match the RFC there.

And perhaps there's more things?

**Comment by dlrobertson** [comment]
Ah! Thanks, that is interesting

**Comment by mnot** [comment]
FWIW, the HTTP specs use 'header fields' etc. consistently, but also [acknowledge](https://httpwg.org/specs/rfc9110.html#header.fields) that they're often referred to just as 'headers'.

**Comment by annevk** [comment]
Let's see:

* `field-name`: unchanged.
* `method`: unchanged.
* `field-content`: unchanged.
* `field-value`: changed, but we don't rely on this currently despite it being listed in the source so maybe it doesn't matter. Our restrictions on header values are much looser than HTTP. The note near "header value" needs to reference https://github.com/httpwg/http-core/issues/215 though. That's closed, but it's not clear to me the HTTP WG is willing to engage further on this topic.
* `reason-phrase`: unchanged, but no longer defined in semantics. I guess it's a pure HTTP/1.1 thing now.
* `delta-seconds`: unchanged.

I think most of the tricky issues with fields are avoided because we don't talk about trailers at the moment. If we ever got trailer support it might give rise to some confusion as we'd use header list and `Headers` for them. As header list and `Headers` is really our "fields". Still, we should add a note that we use the colloquial term.

Ah, and I just noticed there's a bunch of hardcoded links for HTTP caching as also noted above. Hopefully those are somewhat straightforward.

**Comment by annevk** [comment]
#1587 is meant to address this.
