### ISSUE TITLE
"no-cors" and credentials mode

### ISSUE THREAD

**Issue by wanderview** [whatwg/fetch#169]
Step 4.3 of HTTP fetch reads:

```
Let credentials flag be set if one of
 - request's credentials mode is "include"
 - request's credentials mode is "same-origin" and either the CORS flag is unset or
   response tainting is "opaque" 
```

That second bullet should read "or response tainting is NOT opaque".  The logic on the opaque check is reversed.

**Comment by tyoshino** [comment]
This text (db3353b7e42e8e5efce58e60a734002a1b6be303) is based on your suggestion made in #130. The situation has changed since then?

**Comment by tyoshino** [comment]
Hmm, you actually intended to mean in https://github.com/whatwg/fetch/issues/130#issue-107232548 that `no CORS` case should be excluded (i.e. credentials flag shouldn't be set) but it's incorrectly triggered by `request's credentials mode is "same-origin" and the CORS flag is unset`?

**Comment by wanderview** [comment]
Yea, I think my suggestion had the same logic bug.  (In gecko our flag is reversed... LOAD_ANONYMOUS means to exclude credentials.  It confuses me, sorry.)

What we want to do for same-origin credentials is only send credentials when we have never been cross-origin for either the cors or no-cors case.  In the cors mode case we can look at CORS flag, but for no-cors we use opaque tainting to indicate "ever cross-origin".

I think the current text is wrong, both for the origin reason I stated and also the one you point out about the CORS flag being unset for no-cors.

**Comment by tyoshino** [comment]
Hmm, until https://github.com/whatwg/fetch/commit/f334e0b2052076ea15eb39798c9e149290134878, it seems the `omit credentials flag` was only relevant when the mode is CORS. The direction we took was to introduce new combinations and make them useful?

I now agree that current spec is weird since `credentials mode` set to `omit` suppresses credentials even for `no CORS`, while `include`/`same-origin` has no effect for `no CORS`.

What's the potential use cases of no-CORS+same-origin combination? Jake's proposal contains it but I'm not sure whether or not it's written assuming that same-origin has no effect for no-CORS.
https://github.com/whatwg/fetch/issues/106#issuecomment-128735776

Currently no specific use case, but we should fix it so that `same-origin` + `no CORS` provides us new ability to us?

**Comment by wanderview** [comment]
I agree no-cors with same-origin creds. is new to the platform.  I think it should work or immediately throw/reject as an illegal combination.

**Comment by annevk** [comment]
"no-cors" combined with "omit" is new too. I can go either way with regards to making credentials mode work for "no-cors". It makes some sense, but it also makes sense to me to simply disallow any specified credentials mode with "no-cors" since it's largely legacy anyway.

**Comment by annevk** [comment]
Ping, opinions?

**Comment by jakearchibald** [comment]
Happy to fail on "omit" + "no-cors". I can't think of any use-cases for it.

**Comment by annevk** [comment]
That would also mean that whenever you specify `mode : "no-cors"` you'd also have to specify `credentials: "include"` or you would get an exception. At least with the current defaults. Hmm.

**Comment by annevk** [comment]
Please look at #193 for my solution. I plan on allowing the combination of "no-cors" and "omit", but not "no-cors" and "same-origin".

**Comment by annevk** [comment]
Oh, and please review it, it's a PR and has not landed yet.

**Comment by jakearchibald** [comment]
> That would also mean that whenever you specify mode : "no-cors" you'd also have to specify credentials: "include" or you would get an exception

Oh, yeah, that's no good. I keep forgetting about the defaults there.

**Comment by wanderview** [comment]
Personally I think it would be nice to make these combinations work.  Maybe a web app needs to work with a no-cors resource, but wants to avoid leaking cookies if credentials are not needed.  Having primitives to do this would be useful.

**Comment by annevk** [comment]
@wanderview in particular, you want "`same-origin`" to work with "`no-cors`"? And all that is required to enable that would be making the change you suggested in OP? I would be okay with that too, I really don't care much either way here.

**Comment by wanderview** [comment]
If we make no-cors work with "same-origin" creds, then I think we should support "omit" creds too.

And I don't think my OP is adequate as pointed out by @tyoshino here:

  https://github.com/whatwg/fetch/issues/169#issuecomment-161903374

**Comment by annevk** [comment]
The PR I created supports both omit/include, but not same-origin. Your comment confuses me a bit.

If we want all combinations to work, would the following conditions for setting the credentials flag work?

* request's credentials mode is "include"
* request's credentials mode is "same-origin", request's mode is _not_ "no-cors", and the CORS flag is unset 
* request's credentials mode is "same-origin", request's mode is "no-cors", and response tainting is "opaque"

**Comment by wanderview** [comment]
Why not make the second bullet "requrest mode is 'cors'"?  Or better yet, just use response tainting for both the second and third bullet.  Don't use the CORS flag at all.

**Comment by annevk** [comment]
Because it should also be set for "navigate" and "same-origin", as far as I can tell. However, making it

* request's credentials mode is "include"
* request's credentials mode is "same-origin and request's response tainting is "opaque" or "cors"

does seem easier. Forgot that response tainting also had "cors".

**Comment by wanderview** [comment]
I think that should work.  (I've had 2 cups of coffee now...)

**Comment by annevk** [comment]
Oops, it should be 'request's credentials mode is "same-origin" and request's response tainting is "basic"' of course. Forgot to invert something again.

**Comment by tyoshino** [comment]
So, the patched algorithm is:

- request's credentials mode is `"include"`
- request's credentials mode is `"same-origin"` and request's response tainting is `"basic"`

Now it's clear that `"same-origin"` credentials mode works just based on whether the request being sent is same origin or cross origin except for the `"navigate"` mode.

Anne, it seems the the `"same-origin"`+`"navigate"` combination will continue ignoring whether the current request is same origin or cross origin since its response tainting is "basic" and therefore the credentials mode is always set. Is this intentional? Based on the idea that `"navigate"` mode requests are always handled as if it's same origin regardless of `current url`?

Given that the combination `"omit"`+`"no-CORS"` which looks meaningless is the default and we cannot kill it, I think keeping also the combination `"same-origin"`+`"no-CORS"` is more consistent. Agreed.

**Comment by annevk** [comment]
@tyoshino "navigate" is a special case and basically always includes credentials since HTML will not invoke it any other way. If that changes at some point we'll need to make some changes to Fetch too.

**Comment by tyoshino** [comment]
@annevk Thanks. I got it. All we need to do is make sure we remember this discussion when that happens :)

**Comment by annevk** [comment]
Yeah, I was thinking the same. I'll add some notes while fixing this.

**Comment by wanderview** [comment]
I think we already support this in gecko, but I wrote a bug to add some tests:

  https://bugzilla.mozilla.org/show_bug.cgi?id=1238950

**Comment by xgqfrms** [comment]
# express.js get post body bug

```js
fetch(`http://127.0.0.1:3000/api/post`, {
    body: JSON.stringify({key: "value"}),
    cache: "no-cache",
    headers: {
        "Content-Type": "application/json",
    },
    method: "POST", 
     //  ❌,  can not read post body data
    mode: "no-cors",
})
.then(res => console.log(`res =`, res))
.catch(err => console.error(`error =`, err));

```


```js
fetch(`http://127.0.0.1:3000/api/post`, {
    body: JSON.stringify({key: "value"}),
    cache: "no-cache",
    headers: {
        "Content-Type": "application/json",
    },
    method: "POST",
    // ✅ can read post body data
    // mode: "cors",
})
.then(res => console.log(`res =`, res))
.catch(err => console.error(`error =`, err));

```

```js
fetch(`http://127.0.0.1:3000/api/post`, {
    body: JSON.stringify({key: "value"}),
    cache: "no-cache",
    headers: {
        "Content-Type": "application/json",
    },
    method: "POST",
    // ✅ can read post body data
    // mode: "no-cors",
})
.then(res => console.log(`res =`, res))
.catch(err => console.error(`error =`, err));

```

![image](https://user-images.githubusercontent.com/7291672/113675801-50fbe380-96ee-11eb-8049-ff79ba381e59.png)
