### ISSUE TITLE
Should `body` parameter in the Response constructor nullable?

### ISSUE THREAD

**Issue by yutakahirano** [whatwg/fetch#178]
Currently the type of `body` parameter in the Response constructor is `optional BodyInit`. That means we cannot create a null body response with specifying the second `init` parameter.

Reported at https://code.google.com/p/chromium/issues/detail?id=524500.
Declaring the parameter as nullable fixes it, I think.

**Comment by annevk** [comment]
Just use `undefined` as parameter. APIs where null and undefined are the same is old school. @domenic perhaps this is worth writing about in the style guide?

**Comment by yutakahirano** [comment]
Thanks.

**Comment by domenic** [comment]
I think this case is a bit subtle since `res.body` can return `null` so it's a little strange to disallow passing in `null`.

Another way to think about it is that `undefined` is supposed to be a default-value triggerer. In this case the default value seems to be ... `null`. And it's weird that you can only set the default value implicitly, not explicitly. It would be a different story if `res.body` returned `undefined` for null body, but it doesn't. (And I think that's probably a good thing.)

**Comment by annevk** [comment]
Interesting, so all in all we should probably make a change here. (Apart from IDL making it hard for `res.body` to return `undefined` it seems that it returning `undefined` might make folks suspect the property does not exist. Is that your reasoning why we should stick to `null` there and therefore allow it as part of the constructor too?)

**Comment by domenic** [comment]
> it seems that it returning undefined might make folks suspect the property does not exist. Is that your reasoning why we should stick to null there and therefore allow it as part of the constructor too

Yeah, pretty much. There's also some vague distinction in my head between `null` as "explicitly no object" and `undefined` as "this property isn't even initialized/doesn't even exist/is left as its default" or something like that.

**Comment by yutakahirano** [comment]
Then the null argument should be handled in https://github.com/yutakahirano/fetch-with-streams, right?
I agree that ```new Response(oldResponse.body)``` should be valid.

**Comment by annevk** [comment]
I think I fixed it accurately in Fetch. Not sure what else would need changing.
