### ISSUE TITLE
"A value is a byte sequence that matches the field-content token production."

### ISSUE THREAD

**Issue by domenic** [whatwg/fetch#213]
https://fetch.spec.whatwg.org/#concept-header-value

What about headers for which this is not true? It seems like browsers allow any byte sequence, as discussed in https://github.com/nodejs/http-parser/issues/281.

Fetch should probably be the spec that defines the error handling for "invalid" server responses.

**Comment by annevk** [comment]
See https://github.com/whatwg/fetch/issues/115#issuecomment-183469334 for a similar discussion.

Actually defining HTTP parsing is something I thought of doing at some point, and @gsnedders put some effort in, but it would be quite a bit of work and given that HTTP/2 changes this dramatically as I understand it due to the header compression tables it's unclear how much interest there is in cleaning up 0.9-1.1.

**Comment by gsnedders** [comment]
HTTP/2 doesn't change it that much: it removes all the questions about *message syntax* parsing, but not about *header syntax* parsing.

**Comment by annevk** [comment]
I'm duplicating this against #332 as that contains more information about the issue with the current definition.
