### ISSUE TITLE
Merge HTML5 and Fetch definitions of 'HTTPS state'

### ISSUE THREAD

**Issue by jwatt** [whatwg/fetch#241]
We have both:

https://fetch.spec.whatwg.org/#concept-response-https-state

and

https://html.spec.whatwg.org/multipage/webappapis.html#https-state

It would be good if fetch defined HTTPS state in a way that HTML5 could reuse.

**Comment by domenic** [comment]
This doesn't really make sense. The one in HTML is a value stored on the settings object (~ the window) that is passed to certain Fetch requests made with that settings object. You can't get rid of HTML's since otherwise you wouldn't know what to pass to fetch.

In JavaScript programming terms, basically Fetch defines something like `specFetch(..., httpsState, ...)` and HTML defines `const currentSettingsObject = { ..., httpsState: <something>, ... }` and then later calls `specFetch(..., currentSettingsObject.httpsState, ... })`.

**Comment by annevk** [comment]
I think what @jwatt meant is to define the set of values in one place.

**Comment by jwatt** [comment]
Yeah, sorry, that could have been clearer.
