### ISSUE TITLE
Consider adding HTML's 401 verbiage

### ISSUE THREAD

**Issue by domenic** [whatwg/fetch#311]
HTML, before https://github.com/whatwg/html/pull/1346, had the text

> Resources whose status is 401 that do not include a challenge recognised by the user agent must be processed as if they had no challenge, e.g., rendering the entity body as if the status had been 200.

This probably falls under Fetch's current XXX:

> Needs testing: multiple `WWW-Authenticate` headers, missing, parsing issues.

But it might be good to port over this specific requirement? Or not; unsure.

**Comment by annevk** [comment]
At some point we should probably test this and figure out what happens. I suspect Ian has done that to some extent and that's probably why HTML has that text. @hallvors and @Manishearth might have done some testing too?

**Comment by Manishearth** [comment]
I haven't gotten that far yet.

**Comment by annevk** [comment]
I think the specification requirement Ian had in HTML is not suitable now we have a much lower-level grip on things. E.g., it's pretty clear the body will be rendered irrespective of status code, since nothing says so otherwise. The XXX Fetch has however is less clear and needs work, but that's outside the scope of this issue.

So I'm closing this wontfix.
