### ISSUE TITLE
Stop using entry settings object

### ISSUE THREAD

**Issue by annevk** [whatwg/fetch#367]
@domenic should we just use the relevant settings object of the context object (the global object)?

**Comment by domenic** [comment]
(Renamed the issue for correctness.)

There are three uses:

- Request constructor. This should use the current settings object, since there is no `this` to get the relevant settings object of.
- Response constructor. Same.
- Response.prototype.redirect. This should use the relevant settings object of the context object.

**Comment by annevk** [comment]
@domenic it's Response.redirect, not on the prototype. So it's effectively a constructor. I'll make that current too.

**Comment by annevk** [comment]
Thanks for the help!

**Comment by domenic** [comment]
We should get web platform tests written for this... you up for it, or shall I?

**Comment by annevk** [comment]
@domenic since you can probably copy-and-paste something, you?

**Comment by domenic** [comment]
Yeah just was offering you the opportunity if you wanted to practice :). I'll do it.

**Comment by wanderview** [comment]
Gecko bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1432272
