### ISSUE TITLE
Editorial: remove direct w3c.github.io links

### ISSUE THREAD

**Issue by annevk** [whatwg/fetch#409]
It seems these are all for WebAppSec drafts and could use the bikeshed autolinking system instead. @mikewest interested in looking at this since I think you put most of these in?

**Comment by mikewest** [comment]
Would you like to link to the `/TR/` document instead? I haven't linked to those just because we haven't set up autopublication via Travis yet. I generally publish manually, and not as often as I should... That's something we should address, it just hasn't been on anyone's priority list...

/cc @hillbrad @dveditz @wseltzer who might have spare cycles. :)

**Comment by annevk** [comment]
No I don't. What I want is to use Shepherd's autolinking feature.

**Comment by annevk** [comment]
I really rather avoid linking to TR/ since that seems worse than the editor's draft.

**Comment by annevk** [comment]
To be extra clear, this is meant as editorial cleanup of the source, I expect the output to be identical.

**Comment by mikewest** [comment]
Ah. I see, and agree. I'll send you a PR.

**Comment by annevk** [comment]
https://github.com/w3c/webappsec-upgrade-insecure-requests/commit/6fabd5bd2f132ea04be1199bc0cedeb3b797080a also helps with this.
