### ISSUE TITLE
Automatically set request's "Content-Type" to "application/json" for POJOs

### ISSUE THREAD

**Issue by appsforartists** [whatwg/fetch#47]
As I read the [Body Mixins](https://fetch.spec.whatwg.org/#body-mixin) section, `options.body` can be introspected for certain types, which will cause the `Content-Type` header to be set appropriately.

Can we have it check for plain-ol'-JS-objects (or any other stringifyable type), run `JSON.stringify(options.body`), and set `options.headers["Content-Type"] = "application/json"`?

**Comment by annevk** [comment]
It's hard (if not impossible) to distinguish plain-ol'-JS-objects from objects we want to do something with. I guess in theory we could have this as the fallback rather than stringifying. @nikhilm @bzbarsky, thoughts? It would complicate the implementation a lot as we could no longer use types, we'd have to use `any` unless IDL gains support for this kind of thing.

**Comment by domenic** [comment]
-1, this is too much magic.

**Comment by annevk** [comment]
Is it? One is type check and fallback to ToString. The other is type check and fallback to ToJSONString.

**Comment by domenic** [comment]
Setting content-types automatically is the magic I don't like... these things should be explicit.

**Comment by annevk** [comment]
So say we discuss that separately. What about the above?

**Comment by domenic** [comment]
I guess I don't see saving a single `JSON.stringify(` and `)` to be worth the feeling of "does this actually work?" I'd get whenever reading such code.

**Comment by bzbarsky** [comment]
In implementation terms I'd probably extend Gecko's IDL with something like ByteString/DOMString/USVString but which uses JSON.stringify as the conversion algorithm.  In spec terms we could either add a new type like that or use any and manually do typechecks.

But it does seem odd to do this automagically as far as setting the type goes.

**Comment by bzbarsky** [comment]
In both spec and implementation terms, what exactly is the request when an actual string is passed in?  Should it be used as-is, with text/plain type, or should it go through JSON.stringify and get the JSON type?  Because if it's the former, that makes both spec and implementation a _lot_ more complicated.

@domenic, in the world where the JSON.stringify is done by the caller, how does the caller set the type?

**Comment by domenic** [comment]
The usual way, with `headers: { "Content-Type": "application/json+myapimimetype" }`

**Comment by annevk** [comment]
@bzbarsky, my idea was that if you pass in a string you'd get the JSON treatment.

It's somewhat appealing to do since we also have `json()` and it would make a likely common case even more trivial.

I disagree with @domenic that `Content-Type` defaulting based on a specific object (not a stream or `ArrayBuffer`, mind you) is bad. The developer still has full control over the `Content-Type` header either way.

**Comment by bzbarsky** [comment]
It seems really weird to me to give the JSON treatment when a string is passed in...

**Comment by annevk** [comment]
Hmm fair, I forgot about the added quotes. I guess we should just leave this as-is then.

**Comment by appsforartists** [comment]
I disagree about it being too magic.  The spec already has "magic" cases for `Blob`, `FormData`, `URLSearchParams`, and `USVString`.  This would extend that to JSON, which adds symmetry with `response.json()` and paves the cowpath, since so many modern APIs expect JSON.

@annevk - is `body.constructor === Object || Array.isArray(body) || body.toJSON === function` a fair test?  That covers the common cases without adding a weird edge for Strings (which you probably don't want to stringify anyway).

**Comment by dgraham** [comment]
When I was writing the JS polyfill from the Fetch spec, I interpreted passing an object as `body` to mean it would be used as a form encoded post request body. That was fixed and removed in https://github.com/github/fetch/pull/30. This assumption was probably based on experience with jQuery's `$.ajax` behavior.

Intuitively, it seems like passing an object should do *something*. Whether it's turned into JSON automatically, wrapped in FormData automatically, or some other behavior is debatable.

This issue would also be helped by enhancing the `FormData` constructor to accept an object like:

```js
fetch('/query', {
  method: 'post',
  body: new FormData({
    name: 'Hubot',
    login: 'hubot'
  })
})
```

That would add symmetry with `JSON.stringify`:

```js
fetch('/query', {
  method: 'post',
  body: JSON.stringify({
    name: 'Hubot',
    login: 'hubot'
  })
})
```

**Comment by appsforartists** [comment]
One solution could be a `type` parameter.  If set to `"json"`, it will wrap your body in `JSON.stringify` and set the appropriate `Content-Type` header.  If set to `"form"`, it will encode your body as form data and set the appropriate header.

**Comment by annevk** [comment]
I agree with @dgraham that eventually `FormData` needs to grow new capabilities, but until some IDL stuff is sorted out that won't happen.

I don't think we want a new `type` parameter just for this. In that case you might as well write the relevant code (it's not too bad after all).

I think I'm wontfixing this for now since there's no obvious correct solution. Perhaps if a library pattern emerges down the line we can revisit.

**Comment by igrigorik** [comment]
Having a case for auto-encode to JSON would be really helpful for Beacon API. As of right now, there is no way to beacon a JSON payload [via Beacon API](https://w3c.github.io/beacon/#sec-sendBeacon-method)... You can JSON.stringify the payload yourself, but then the Content-Type is set as plain text; there is no way to override the content-type.

I'd love to see this reopened.
