### ISSUE TITLE
"process request body" is gone

### ISSUE THREAD

**Issue by annevk** [whatwg/fetch#495]
It seems that because of Streams we no longer need "process request body". However, that does mean we need to update XMLHttpRequest and Fetch so it's no longer used.

Found while investigating https://github.com/whatwg/xhr/issues/118.

**Comment by yutakahirano** [comment]
Thanks.

Either the source of the stream or the reader can notice that event, but XHR is neither of them (the stream is created in https://fetch.spec.whatwg.org/#concept-bodyinit-extract). I think we need one of the following:

 1. Dispatch "process request body" from https://fetch.spec.whatwg.org/#concept-request-transmit-body.
 1. Dispatch "process request body" from https://fetch.spec.whatwg.org/#concept-bodyinit-extract.
 1. Insert a intercepting stream in XHR (i.e., create an identical transform stream in order to detect reading and use pipeTo).
 1. Create a stream in XHR.

What do you think? I prefer the first because it's simpler.

Another problem: Although the source receives the progress notification in a way, it depends on the chunk size. For example, https://fetch.spec.whatwg.org/#concept-bodyinit-extract enqueues one big chunk in the BufferSource case, and the source will not receive any intermediate progress notification.

**Comment by annevk** [comment]
I would be okay with 1 I think. We did update XMLHttpRequest for the similar response situation though. I wonder if there's some kind of alternative abstraction idea we're overlooking here.

(The response situation ends up being problematic elsewhere. E.g., normally the network feeds bytes to the HTML parser incrementally, so now we'd have to update the HTML Standard to talk about streams and such.)
