### ISSUE TITLE
Cloned responses should not have immutable headers

### ISSUE THREAD

**Issue by philipwalton** [whatwg/fetch#608]
https://fetch.spec.whatwg.org/commit-snapshots/0bcd5dfc71ef44319873887f4b83119bd6d0b71d/#response-class

> Upon fulfillment of context object’s trailer promise, resolve clonedResponseObject’s trailer promise with a new Headers object whose guard is "immutable", and whose header list is clonedResponse’s trailer\.

When cloning a response via `response.clone()`, the headers are spec'ed to be immutable, and if you try to modify them, you get an error.

I'd like to prepose that we change this behavior. The primary use case I'm trying to solve is adding custom metadata to a response for analytics purposes (to distinguish a response served from the cache vs. a response that required a network fetch).

You can work around this today by creating a clone of the response and then manually making a copy of that clone, e.g. `new Response(await responseClone.text(), responseClone)`, but this is a lot of work to just modify headers.

Since I *can* work around the immutable headers issue in this way, I'm not sure what protection it's offering.

**Comment by annevk** [comment]
The portion you quoted is about the trailer, not the headers. The headers end up being copied with the same guard as the input. I suspect your concern is with inputs where the guard is "immutable" and therefore the clone being "immutable" too.

If you create a new `Response` object you don't get to set the url list or its type (or trailer, but that's less significant and possibly an oversight). Also, you should be able to do:

> const responseClone = new Response(inputResponse.body, inputResponse);

which means you can do it all synchronously and not have to wait for anything.

**Comment by philipwalton** [comment]
> I suspect your concern is with inputs where the guard is "immutable" and therefore the clone being "immutable" too.

Yep, that's exactly my concern. And more specifically *should* this be the case for cloned response objects?

It's also entirely possible that my use case (adding metadata to a `Response`) could be handled in some different way, which I'm open to.

Effectively, what I'm after is a reasonable way to communicate back to the window whether this particular response came from the cache or from the network.

**Comment by annevk** [comment]
@philipwalton the HTTP cache or the Cache API / Indexed DB?

**Comment by philipwalton** [comment]
For my use case the Cache API.

Essentially what I'm wanting to do is something like this:

```js
const startTime = performance.now();
const response = await fetch(url);
const duration = performance.now() - startTime;
const wasCached = determineSomehowIfResponseCameFromCacheApi(response);

sendDataToAnalyticsService({
  url,
  duration,
  wasCached,
});
```

And since my service worker will sometimes be responding to the fetch event with a cached response, I want to know how often that happens and compare the actual savings via RUM.

**Comment by annevk** [comment]
Okay, we could maybe expose that in some other way (since we know where the object came from). That would solve the specific issue, but not your larger problem. Probably best tracked as a new issue if you want to pursue that.

I don't think we want to change `clone()` since it should also work for opaque responses and such. We could maybe have `limitedClone()` that doesn't preserve all the internal fields of a response and would fail for opaque responses, but that would essentially be identical to my code snippet earlier, which still doesn't seem too bad to me.

**Comment by annevk** [comment]
https://github.com/WebAssembly/content-security-policy/issues/3 is of interest here as apparently WebAssembly wants to be able to rely on immutable headers. There's also some potential optimization paths that would end up failing if a response could change what it is as it makes its way through the system.

**Comment by annevk** [comment]
As this hasn't come up since and there are workarounds I'm going to close this. Mutating a response that has a certain authority seems dangerous so casting it into a synthetic response first seems like the right thing to do. We could add a convenience method for that, but for that we need some kind of demonstration this is a widespread pattern/issue.
