### ISSUE TITLE
History behind the decision to make fetch return a Promise

### ISSUE THREAD

**Issue by jmeas** [whatwg/fetch#611]
:wave: Is there any documentation/conversation around the decision to make fetch return a Promise? I looked through the issues a bit, and didn’t see anything, so I was wondering if there might be a mailing list or something where the initial discussion happens around the creation of this spec.

Thanks!

**Comment by annevk** [comment]
https://github.com/whatwg/fetch/commit/2e82a88634f0cd23de1977b11b36d1e907d01f5c was the commit where it got added to Fetch (note that Fetch is much more than the API, but I'm assuming by "this spec" you mean the API).

https://github.com/w3c/ServiceWorker/commits/master/controller.ts has some early history in the service worker repository.

Looking through IM conversations @wycats further refined the shape of the API. (And I should probably add him to the acknowledgments section!)

It also got discussed and further changed based upon mailing list discussion: https://lists.w3.org/Archives/Public/public-whatwg-archive/2014Jun/ (search for "fetch").

There's also some archived IRC discussion at: http://logs.glob.uno/?c=freenode%23whatwg&s=15+May+2014&e=8+Jun+2014.

Looking through the material I think we also thought it would be much more common to subclass promise than it turned out to be.

I'll leave this open for a bit, perhaps @slightlyoff, @jakearchibald, @wycats, and others can add their anecdotes. Would be interesting.

**Comment by annevk** [comment]
https://gist.github.com/wycats/cf73dd4c974352fcb767 is another important design document (the one we discussed on IM).

**Comment by jakearchibald** [comment]
@jmeas is this asked with an alternative in mind?

**Comment by slightlyoff** [comment]
Just saw this thread per [twitter conversation](https://twitter.com/annevk/status/1060879259747672066). Hopefully recollections are still helpful. Here are mine:

When we sat down to work through the "navigation controller" design -- largely at the Mozilla London offices on St. Martin's Lane -- we quickly settled on a worker type, but knew from experience that it couldn't have synchronous APIs. That meant we were either going to have to design a new subtype of XHR (which was universally loathed) that was both promisified and sync-XHR-free, or we would have to design a new thing. 

The argument for "new thing" was that everyone sort of wanted it anyway, that retrofitting XHR for promises and `Request`/`Response` types was bound to be a huge effort, that defining an async-only version of XHR for one context (but not all) was going to be "weird", and that we wouldn't get the chance/excuse again. On the other side was "well, XHR works, sooo....".

Those arguments were effectively the same ones that were repeated over and over again until `fetch()` shipped.

We played around with many different forms and shapes of the API, IIRC, and pretty quickly got comfortable with the new method given how frequently it showed up in code we were working through.

Perhaps interestingly, the intensity of the various fights over Promises seemed to make `fetch()` less controversial. Once you had `Promise`, `fetch()` seemed inevitable and the wrapping/unwrapping and cancellation debates quickly eclipsed discussion of whether or not `fetch()` was a good idea.
