### ISSUE TITLE
Moar hyphens

### ISSUE THREAD

**Issue by annevk** [whatwg/fetch#63]
Per @sideshowbarker we should add some hyphens. E.g. "skip service worker flag" -> "skip-service-worker flag". A lot of that.

**Comment by annevk** [comment]
Would love some input from @jgraham here.

**Comment by sideshowbarker** [comment]
If you want, I can do a pass through the spec and add them where it seems to me like they’re needing, and make a PR with the patch. So there would be something concrete to review.

**Comment by annevk** [comment]
That'd be great.

**Comment by annevk** [comment]
Not closing because of "HTTP network or cache fetch" and "HTTP network fetch", "local URLs only flag", "force Origin header flag", "image request context", others?

**Comment by annevk** [comment]
@sideshowbarker what about the other terms I mentioned above?

**Comment by sideshowbarker** [comment]
> @sideshowbarker what about the other terms I mentioned above?

oops yeah will look at those now too

**Comment by sideshowbarker** [comment]
yeah, also found "fetch done task" which should be "fetch-done task". Will update PR #74

**Comment by sideshowbarker** [comment]
> "image request context"

So yeah If we were to hyphenate that one, we'd need to also hyphenate "worker request context", "navigation request context", and "client request context".

But I think it would be wrong to do, e.g., "image-request context", because the shared term in all cases is "request context" (not just context), and "image", "worker", "navigation", and "client" here are all modifying/qualifying "request context". That is, there are all describing different types of request contexts.

So if were were to add any hyphen at all for these cases, it should probably be to hyphenate "request-context" so that we'd have "image request-context", etc.

"worker request context" seems clear enough without a hyphen, even in isolation, but reading "image request context" in isolation, it's ambiguous (to some readers at least) whether it means "a context for an image request" (in which case it would better be "image-request context") or "a request context for an image", in which case "image request-context" makes it more clear that's what it means.

I realize some of this sorta gets to the point of splitting hairs, but that's kind of what specs are about anyway.

So, all that said, do you think we should make it "request-context" consistently?

**Comment by annevk** [comment]
Yeah, I guess that makes sense.

I also noticed "potential client request" -> "potential-client request".
