### ISSUE TITLE
CORS: why is Authorization request header forcing preflight?

### ISSUE THREAD

**Issue by dvoytenko** [whatwg/fetch#770]
(Not sure if this is the right forum, but https://www.w3.org/TR/cors/ doesn't provide a github link)

Some types of `Authorization` header are some of the key tools for cross-site communication. However, this header is not considered "simple" and forces the preflight. This forces lots of odd workarounds, mostly by including the credentials/tokens in URL parameters or POST body. That makes it harder to standardize around.

Would you ever consider removing preflight requirement from `Authorization` header? Perhaps this could be done safely enough by blacklisting some types of prefixes, e.g. "Basic" or whitelisting others such as "Bearer" or "JWT"? Or we could come up with another required prefix, e.g. "CORS ..."?

**Comment by sleevi** [comment]
I'm sure @annevk can chime in more authoritatively, but when I examined the history of this, it's precisely because it allows for third-parties to attempt to brute-force enumerate passwords for other services.

As a security mechanism, blacklisting is not viable. It merely serves to prevent new authentication methods from being introduced and tightly couples layers that are best separated.

The `Authorization` header also has special treatment by both browsers and servers.

Do you have more details about how/why it is a "key tool for cross-site communication"? This may help understand and document more the design space, as this is a security mitigation to protect users and devices.

**Comment by dvoytenko** [comment]
@sleevi It's a general question, but specific problem that comes to mind is access token in OAuth2. There's a clear misconnect b/w https://tools.ietf.org/html/draft-ietf-oauth-v2-bearer-16#section-4.3 that says:

> Don't pass bearer tokens in page URLs:  Bearer tokens SHOULD NOT be passed in page URLs (for example as query string parameters). Instead, bearer tokens SHOULD be passed in HTTP message headers or message bodies for which confidentiality measures are taken. Browsers, web servers, and other software may not adequately secure URLs in the browser history, web server logs, and other data structures.  If bearer tokens are passed in page URLs, attackers might be able to steal them from the history data, logs, or other unsecured locations.

Vs https://tools.ietf.org/html/rfc6750#section-2.3:
> When sending the access token in the HTTP request URI, the client adds the access token to the request URI query component as defined by "Uniform Resource Identifier (URI): Generic Syntax" [RFC3986], using the "access_token" parameter.

There are countless services relying on OAuth2 and using access_token query parameter. Many of these services also accept access token as an Authorization header, but it's essentially useless in the browser given the CORS preflight requirements.

The access_token URL query parameter is a practical solution and it does help in testing, etc. But given this standard it simply appears to move something that belongs in headers into the query string. And, of course, it also theoretically could be used for enumeration. But practically it's a non-issue given strong cryptography and a limited life time.

**Comment by sleevi** [comment]
> It's a general question

I ask because HTTP authorization schemes are meant to be registered - http://www.iana.org/assignments/http-authschemes/http-authschemes.xhtml - and the question is to determine which of the methods in that registry apply here.

> And, of course, it also theoretically could be used for enumeration. But practically it's a non-issue given strong cryptography and a limited life time.

I don't think that's a fair statement. The UA doesn't know how the server will interpret it - that is, there's no way to know which registered (as they hopefully are) method the server will interpret the credential challenge as. So the enumeration risk is the browser granting access to a 3P website without the 1P's consent - hence, the preflight.

That said, there are other headers that are just as applicable, and my (very limited) understanding of OAuth2 is that it hasn't pursued an Authorization based approach. However, that hopefully explains (some of) the Web Platform risk of allowing 3P to send 1P arbitrary "Authorization" headers and why they're explicitly called out as 'credentials' for the same reason. This also captures why URLs embedded with credentials are also restricted across origin boundaries.

**Comment by annevk** [comment]
> but it's essentially useless in the browser given the CORS preflight requirements.

Why? Latency? Once we have origin policies this should go away.

**Comment by dvoytenko** [comment]
@sleevi here's another good example of misconnect. See OpenID connect spec: http://openid.net/specs/openid-connect-core-1_0.html#UserInfo section 5.3. It goes to directly describe requirements for Authorization header use and CORS support.

**Comment by annevk** [comment]
I'm inclined to close this as we cannot allow distributed dictionary attacks and we've already had trouble enough with the headers that you are allowed to preflight.

It sounds like the problem here is primarily one of OpenID/OAuth figuring out what their ideal setup and having conformance tests and such for that (and maybe providing slightly more detailed documentation on how to implement the protocol).

**Comment by dvoytenko** [comment]
You can certainly close. But I'd really request to consider the implications here. With ITP we are moving to the world where credentialed CORS is essentially nonexistent. OAuth2 and bearer credentials in general may soon be the only reliable CORS strategy.

**Comment by dvoytenko** [comment]
@sleevi This is essentially correct, but it's NOT a workaround for ITP - it's the whole point of OAuth2. My point is that `Authorization` header is part of OAuth2 spec, but it's rendered mostly unusable due to preflight restrictions.

**Comment by sleevi** [comment]
Sure, but it sounds like the OAuth2 spec is not considering how the Web
Security model works. You have alternatives, as noted, and it remains
unclear to me why the preflight is somehow fatal.

The comparison to Cookie is apt - browsers restrict how that access is
granted even moreso. It is not clear to me why, given the alternatives that
exist, Authorization is somehow essential. Is there something missing here?
For example, if it is not to work around ITP, why bring up ITP at all?

**Comment by sleevi** [comment]
@dvoytenko Just to make sure I understand the argument, is this a fair summary of the points.

* Sites use Cookies to restrict access to resources
* ITP makes Cookies more difficult for third-party access
* As such, sites have a hard time using Cookies to restrict access to resources from third-party contexts.
* Sites would thus like to switch how they restrict access
* One way to restrict access is via OAuth2 tokens
* Exposing OAuth2 tokens in querystrings is seen as bad by OAuth2 developers
* Ergo, you would like to expose OAuth2 tokens in headers
* You would like to use the `Authorization` header to expose these tokens
* The browser does not allow programmatic control of the `Authorization` header

Did I get it right so far? It's not clear to me why those last two steps cannot be met by a header other than `Authorization`. While the HTTP specs countenance the `Authorization` header, that doesn't mean that exposing programmatic access to it is compatible with the Web Security model (hence why we have things like CORS in the first place), and so it's not clear what's missing from using other headers. It also seems that the feature request is itself because of something related to ITP specifically (although it's presented as a more general case), and because of that, there's nothing to suggest that ITP wouldn't block or restrict access to whatever methods you end up also using, if those are seen as being usable for tracking and not just authorization.

**Comment by dvoytenko** [comment]
My goal here is to find out if it could ever be considered by web spec to whitelist `Authorziation: Bearer ...` header as a "simple" CORS request w/o requiring preflight. I think at this point it's clear that  this will not happen. So, I'm ok with closing this issue.

I think realistically this means that this authorization header usage (as defined by https://tools.ietf.org/html/rfc6750#section-2.1) is not going to be used in web platforms, with everyone just continuing use query parameters to pass around bearer tokens. Note that the CORS requests is the whole point of OAuth2 and bearer tokens in general. Assuming the use of bearer tokens on the web would only grow given the current trends, I can only see this as a net-negative for the web, user security/privacy, etc. But perhaps it's not a huge negative and not worth challenging the status quo.

>  and so it's not clear what's missing from using other headers

That'd probably be the worst-case scenario. Someone trying to use a non-standard header for something that's so clearly defined in standards.

> It also seems that the feature request is itself because of something related to ITP specifically (although it's presented as a more general case), and because of that, there's nothing to suggest that ITP wouldn't block or restrict access to whatever methods you end up also using, if those are seen as being usable for tracking and not just authorization.

As mentioned above a few times, bearer token use cases are _not_ tracking use cases: they are obtained by a user explicitly opting into using a 3p service for some value, e.g. to access photos for printing, or completing a payment transaction, or claiming an existing authorization to view content. My point is simply that ITP would likely increase use of bearer tokens, since it will be the only stable way to support such use cases.

**Comment by annevk** [comment]
We really cannot add `Authorization` to the safelist for aforementioned reasons. Alternatives can be considered, but at this point it seems better to start a new issue on those, if any.
