### ISSUE TITLE
fetch+CSP end up touching globals in a parallel section on redirect

### ISSUE THREAD

**Issue by bzbarsky** [whatwg/fetch#832]
Say a fetch starts via <https://fetch.spec.whatwg.org/#concept-main-fetch>.  Starting in step 5, we go parallel, so should be able to execute on an arbitary thread/process without touching ambient state.  If the response is an HTTP redirect, we will end up in https://fetch.spec.whatwg.org/#concept-http-redirect-fetch which again calls into main fetch, but already running in parallel.  But main fetch step 2.4 calls https://w3c.github.io/webappsec-csp/#should-block-request which does:

> Let CSP list be request’s client’s global object’s CSP list.

This is doing an unsynchronized access to the CSP list, which could be in the middle of being mutated due to a meta tag insertion, for example.

We need to either snapshot the CSP list when the request is created or do the redirect fetch off a task that ensures it runs when the CSP list is stable or something.

**Comment by bzbarsky** [comment]
@mikewest @annevk

**Comment by bzbarsky** [comment]
Worth checking whether this situation is covered by tests, by the way.

**Comment by mikewest** [comment]
@andypaicu, mind taking a look? I think this is something you wanted to address anyway for navigation requests?

**Comment by annevk** [comment]
(I wish GitHub offered a sigh emoji. `<meta>` FTW. Thanks for reporting this though!)

**Comment by yutakahirano** [comment]
I prefer using the snapshot. We may move the redirect checks to a completely different process.

**Comment by andypaicu** [comment]
From the CSP spec point of view, I'm happy to make any changes to use a snapshotted version of the CSP list. I suppose, from my uninformed point of view, responses already have a [CSP list](https://fetch.spec.whatwg.org/#concept-response-csp-list), so a request could also have a snapshot of the CSP list (which could slightly be trimmed down, I doubt `base-uri` for example is relevant).

In my ideal world mutable CSP policies don't seem like something anyone would ever use in a legitimate manner, but there is a need to allow `<meta` tags to add CSP because there are servers that don't give control of HTTP headers of the pages they host. Assuming there is no legitimate use case for mutable CSP policies, another idea might be perhaps to "lock" the CSP policies as soon a request is made (or maybe as soon as a CSP check is performed). Thoughts on this?

**Comment by bzbarsky** [comment]
@ckerschb might have some thoughts on that; we were just discussing it yesterday.

**Comment by youennf** [comment]
I agree with @yutakahirano.
In Safari, CSP is checked in NetworkProcess so it is guaranteed to stay invariant for a given fetch.

**Comment by annevk** [comment]
@antosart I guess this will be easier to fix once policies are in a container and support some kind of copy operation?

**Comment by antosart** [comment]
@annevk Yes, this looks like something we should be able to address then. Let's keep this in mind.

**Comment by annevk** [comment]
I meant to close this as part of landing #1231 (commit 3c0dd166f9c98014be9dceaae508d656b0adc1d1).
