### ISSUE TITLE
Tests do not always require Origin header when mode is "cors"

### ISSUE THREAD

**Issue by ghost** [whatwg/fetch#871]
Firefox `fetch` is not longer sending CORS header with HEAD or even GET requests
because of vague verbiage here:

https://github.com/whatwg/fetch/blob/4defab749e723dc367819363a3339db8c9ec611c/fetch.bs#L2412-L2416

https://github.com/whatwg/fetch/blob/4defab749e723dc367819363a3339db8c9ec611c/fetch.bs#L4145-L4149

https://bugzilla.mozilla.org/show_bug.cgi?id=1508661

**Comment by annevk** [comment]
I don't see how it's vague, but it does seem the latter statement wasn't read correctly. Coupled with issues with the tests, that led to the change in Firefox.

However, all browsers now pass `fetch/api/basic/request-headers.any.js` suggesting this is not an issue with Firefox alone. Ugh.

**Comment by annevk** [comment]
cc @bakulf @yutakahirano @youennf @cdumez

**Comment by annevk** [comment]
Looking at changes to that file, it seems this was an error introduced two years ago: #225 and also https://github.com/web-platform-tests/wpt/pull/4299.

**Comment by cup** [comment]
https://github.com/web-platform-tests/wpt/pull/4299
https://github.com/whatwg/fetch/issues/225
https://github.com/whatwg/fetch/issues/871#

**Comment by yutakahirano** [comment]
Sorry, I don't understand what's the problem...

**Comment by annevk** [comment]
It seems that when mode is "cors", we don't always include the `Origin` header. I suspect this is only happening for same-origin requests, but it was still surprising to me and I'm not sure it's the right thing to do.

**Comment by yutakahirano** [comment]
Hm, I've been thinking it's intentional. [Chrome implementation](https://cs.chromium.org/chromium/src/services/network/cors/cors_url_loader.cc?q=cors_url_loader.cc&sq=package:chromium&g=0&l=372) is aligned with the current spec. I don't have a good reason not to add an origin header when mode is "cors" and CORS flag is unset.

**Comment by annevk** [comment]
Hmm, per https://github.com/whatwg/fetch/issues/225#issuecomment-265505295 I guess it was, and indeed all implementations do this now, but it doesn't make sense to me.

**Comment by yutakahirano** [comment]
Any opinions?

Providing origin information to the resource owner is becoming more and more important in the context of [CORS-only mode](https://github.com/whatwg/html/issues/4175), I think. @annevk, what do you think?

**Comment by annevk** [comment]
I think we should fix this, but I haven't gotten around to it. Note though that this would only affect same-origin requests, but still seems good to do.

**Comment by yutakahirano** [comment]
Yeah, but the resource owner will be able to distinguish whether the browser enforces CORS to the request.

**Comment by thw0rted** [comment]
Has there been any movement on this?  If you're looking to CORS-enable an application, all the documentation you find online -- as well as a number of libraries that handle it for you -- say that you should base your response on the Origin request header.  If a bunch of browsers are now sending CORS requests with no Origin, how am I supposed to figure out the value to send for ACAO?  I can parse it out of the Referer, assuming that's set, but is it a good long-term solution?

**Comment by annevk** [comment]
@thw0rted for that specific case there should be an `Origin` header as that goes across origins.

I'm no longer interested in changing the same-origin case so I'm going to close this.

**Comment by thw0rted** [comment]
@annevk it's been ages since that last post, but if I understand context correctly (re-reading this, and https://github.com/expressjs/cors/issues/170), I commented here because there was no test validating that a cross-origin request between two different `localhost` ports included the (required) `Origin` header.

I thought that was the point of this issue.  Is there now a test that checks for this condition?  Do you know if browsers are including the header now?

**Comment by annevk** [comment]
We cannot test `localhost` specifically on web-platform-tests, but I don't see why it should behave differently from other origins. If you still encounter this it's probably a good idea to file browser bugs.

**Comment by thw0rted** [comment]
I can see where it would be an infrastructure problem to have to conduct the tests against `localhost`, especially on two ports at once.  Whatever was going on in 2019 must be resolved now, because I'm seeing the right headers, at least in Chrome and Firefox.  If it breaks again later, I'll go directly to the browser.  Thanks!
