### ISSUE TITLE
Should `Content-Disposition: attachment` implicitly opt into CORB and/or CORP?

### ISSUE THREAD

**Issue by anforowicz** [whatwg/fetch#875]
Web servers can use `Content-Disposition: attachment` response header to indicate to browsers that the responses shouldn't be displayed inside the Web page (or as the Web page), but instead should be downloaded:
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition
- https://tools.ietf.org/html/rfc6266

QUESTION: Should presence of `Content-Disposition: attachment` implicitly opt the response into [CORB](https://fetch.spec.whatwg.org/#corb) and/or [CORP](https://fetch.spec.whatwg.org/#cross-origin-resource-policy-header)?

My main worry is that currently `Content-Disposition: attachment` does force a download in Firefox and Chrome, but only for _navigations_ and not for subresources.  In the example below, `200.png` is served with `Content-Disposition: attachment`, but the image is still displayed within the page (OTOH, clicking the link does force a download, rather than displaying the standalone image).  Given this, this change probably has a high risk of breaking some existing websites :-/
```html
<img src="200.png">
<a href="200.png">link</a>
```

cc @csreis, @arturjanc

**Comment by annevk** [comment]
Yeah, pretty sure sites use this tactic as well.

**Comment by arturjanc** [comment]
That's a valid point -- I didn't realize that `Content-Disposition: attachment` was ignored for subresources, so breaking existing sites seems likely (OTOH maybe limiting this to cross-origin loads could reduce the fallout).

We'll get some information about the scope of the potential breakage once `Sec-Fetch-Mode` ships, but otherwise we can probably consider this infeasible.
