### ISSUE TITLE
force-Origin-header flag set for no-cors requests

### ISSUE THREAD

**Issue by tyoshino** [whatwg/fetch#91]
Is it intentional that the "force-Origin-header flag" is set for a Request with mode set to "no-cors"? The name "force" looks like it's for overriding the default behavior. But I want to confirm with you.

This commit started using the flag for the first time.
https://github.com/whatwg/fetch/blob/4deb3ff5e7cb9d868d1f87048e641fc70c8b7928/Overview.src.html (and https://github.com/whatwg/xhr/commit/c99000a96dada32b0aed566563c759256f0b2d9a in XHR and https://github.com/whatwg/fetch/commit/a607d1828209a344e17d6e0a2f8325e547c1014f for Fetch API)

At this point, the Fetch API was not defined yet. I wonder if this flag was intended to be used by XHR for some reason... and not for the Fetch API.

----

If it's intentional, maybe "4.2.2 HTTP requests" should include some note saying that requests made using a self-created Request with mode set to no-cors includes an "Origin" header though it doesn't pertain in the CORS protocol.

**Comment by annevk** [comment]
That is a good question. I added the flag since everything has an origin, but not all fetches want to include an `Origin` header (due to compatibility concerns, mostly).

I guess I (or someone else) needs to study HTML again to find out exactly when we want to include this. I believe the rule was any same-origin, cross-origin CORS, or cross-origin non-GET request, but I'm not sure. I suspect we don't want `fetch()` to override it in all cases so service worker passthrough fetches remain as similar as possible.

**Comment by tyoshino** [comment]
I see. Then, it seems we preserve the flag when creating a Request from another Request. Hm.

Currently, Chrome sends the Origin header even on same origin requests when the method is not GET or HEAD. This seems to be conforming to the current spec for non-GET/HEAD and violating for GET/HEAD. This behavior originates from this WebKit patch made in 2008: https://bugs.webkit.org/show_bug.cgi?id=20792.

I just noticed that you have discussion at https://bugzilla.mozilla.org/show_bug.cgi?id=446344 for Firefox.

As far as I know, currently Firefox doesn't send the Origin header on same origin GET/HEAD/POST/PATCH request.

**Comment by annevk** [comment]
So perhaps instead of the "force flag" we should base appending the `Origin` header on request's method and whether or not the request goes across origins?

**Comment by annevk** [comment]
@tyoshino so instead of this flag, it seems like we could have something like the following: 

If request's origin is not same-origin with request's current url's origin and either request's method is POST or request's mode is one of "cors" and "cors-with-forced-preflight", append the Origin header...

What do you think?

**Comment by annevk** [comment]
https://html.spec.whatwg.org/multipage/semantics.html#downloading-hyperlinks does not want to set the `Origin` header. That's one example that would violate the above proposed rules.

**Comment by annevk** [comment]
HTML also uses the "browsing context scope origin" to determine whether or not the `Origin` header is to be set.

**Comment by annevk** [comment]
Perhaps the best here is to instead of having this flag, we give origin a "no-origin" value that means omitting the header altogether, similar to what we do for referrer et al.

Probably copying the origin from another request is okay, just not sure if we need to reset it if you change anything. I guess we should, otherwise you could circumvent XSS measures.

**Comment by yutakahirano** [comment]
The conclusion is to add the Origin header unless the omit flag is set, and there is no way to set the flag via XHR / fetch() with a user constructed Request at least for now, right?

|                                          | Spec  | Chrome 45 | Firefox 41 |
|-----------------------------------|-----------------------------|-------------------|------------------|
| fetch(new Request(url, {method: 'GET'}))       | add                            | omit       |  add              |
| fetch(new Request(url, {method: 'PATCH'}))  | add                            | add                |  add              |
| XHR (method = GET)      | add                            | omit       | omit      |
| XHR (method = PATCH) | add                            | add                | omit      |

**Comment by annevk** [comment]
Yeah. As far as I know XMLHttpRequest always required it to be set. It was just a couple of legacy contexts where we could not require it / did not want to add it.

**Comment by tyoshino** [comment]
The change "force -> omit" and making the default to `unset` sounds ok.

----

Since it seemed many people were treating presence of "Origin" as indication whether or not the server has to handle CORS (see https://code.google.com/p/chromium/issues/detail?id=512836 ), it was not easy for us (and maybe also for Firefox) to change the XHR implementation conform to the spec.

Per Yutaka's post above, Firefox introduced `fetch()` being conforming to the spec. It's good opportunity. Chromium should also try to align our `fetch()` with it, I think.

**Comment by tyoshino** [comment]
Regarding the privacy concern shown by Adam in https://bugs.webkit.org/show_bug.cgi?id=20792, I think it's no problem for same origin requests. XHR originating from site A sent to site A doesn't leak anything to A.

And, we're already sending Origin for cross-origin GET requests.

**Comment by annevk** [comment]
Interesting, I thought it was already included for same-origin XMLHttpRequest. If we need to undo that an issue filed against https://github.com/whatwg/xhr would be appreciated.
