### ISSUE TITLE
Consider updating HTTP references to RFC 7230.

### ISSUE THREAD

**Issue by Ms2ger** [whatwg/fetch#99]
I was looking at `field-value` in particular, but note https://www.rfc-editor.org/errata_search.php?rfc=7230&eid=4189.

**Comment by annevk** [comment]
See https://www.w3.org/Bugs/Public/show_bug.cgi?id=27797 for a problem.

**Comment by annevk** [comment]
And #100.

**Comment by annevk** [comment]
* Method -> method (otherwise same) 
* field-name (same)
* field-value (same, though we should strip HTTP whitespace (not ASCII whitespace) on both sides)
* delta-seconds (same, but defined in https://tools.ietf.org/html/rfc7234)
* Reason-Phrase -> reason-phrase (otherwise same)

A bunch of bytes are called "obsolete" but will nevertheless be supported.
